export enum ErrorCodes {
  VALIDATION,
  INCORRECT_DATA,
  INCORRECT_PROPOSAL_FORMAT,
  INCORRECT_QUORUM,
  INCORRECT_PROPOSAL_SIZE,
  INCORRECT_PROPOSAL_METADATA,
  INCORRECT_PROPOSAL_PERIOD,
  INCORRECT_VER,
  INCORRECT_TYPE,
  INCORRECT_SIGNATURE,
  UNKNOWN_SPACE,

  INCORRECT_VOTE_METADATA,
  INCORRECT_VOTE_FORMAT
}